apiVersion: "v1"
kind: "Service"
metadata:
  name: example-go-deployment-service
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "example-go"
  type: "LoadBalancer"