apiVersion: "v1"
kind: "Service"
metadata:
  name: example-node-deployment-service
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "example-node"
  type: "LoadBalancer"